### ISSUE TITLE
OOM crash on rotation

### ISSUE THREAD

**Issue by Zhuinden** [JohannBlake/adoptme#2]
```
    --------- beginning of crash
04-03 22:35:52.232 6085-6085/dev.wirespec.adoptme E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.wirespec.adoptme, PID: 6085
    java.lang.OutOfMemoryError: Failed to allocate a 176256012 byte allocation with 4194304 free bytes and 140MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
        at android.content.res.Resources.loadDrawable(Resources.java:2540)
        at android.content.res.Resources.getDrawable(Resources.java:806)
        at androidx.compose.ui.res.ImageResources_androidKt.imageResource(ImageResources.android.kt:39)
        at androidx.compose.ui.res.ImageResources_androidKt.imageResource(ImageResources.android.kt:58)
        at dev.wirespec.adoptme.ui.nav.NavDrawerUIKt.NavDrawer(NavDrawerUI.kt:64)
        at dev.wirespec.adoptme.ui.nav.NavDrawerUIKt.NavDrawerHandler(NavDrawerUI.kt:41)
        at dev.wirespec.adoptme.ui.screens.main.MainUIKt$Main$1.invoke(MainUI.kt:42)
        at dev.wirespec.adoptme.ui.screens.main.MainUIKt$Main$1.invoke(MainUI.kt:41)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:130)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
        at androidx.compose.material.DrawerKt$ModalDrawer$1$2$7.invoke(Drawer.kt:610)
        at androidx.compose.material.DrawerKt$ModalDrawer$1$2$7.invoke(Drawer.kt:372)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:116)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:105)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:102)
        at androidx.compose.material.DrawerKt$ModalDrawer$1.invoke(Drawer.kt:350)
        at androidx.compose.material.DrawerKt$ModalDrawer$1.invoke(Drawer.kt:312)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:130)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
        at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1$measurables$1.invoke(BoxWithConstraints.kt:61)
        at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1$measurables$1.invoke(BoxWithConstraints.kt:61)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(SubcomposeLayout.kt:167)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(SubcomposeLayout.kt:167)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
        at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3422)
        at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2604)
        at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:348)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:698)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3028)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:304)
        at androidx.compose.ui.layout.SubcomposeLayoutState.subcomposeInto(SubcomposeLayout.kt:184)
```

**Comment by DrifterAtSea** [comment]
The background image for the navigation drawer was too large and it would cause a crash on devices with not enough memory. I replaced the background image with a smaller one and also replaced painting the navigation's background with the image with just a normal image composable. You can try the updated code and see if that fixes the issue on your device.
